<!--
<div id="paging1" class="page light-theme simple-pagination">
    <ul>
        <li class=""><span class="prev">共 3 页--当前第 2 页</span></li><li class="gotopage" data-page="1"><a href="javascript:void(0);" class="prev">首页</a></li>
        <li class="gotopage" data-page="1"><a href="javascript:void(0);" class="prev">上一页</a></li>
        <li class="gotopage" data-page="3"><a href="javascript:void(0);" class="page-link next">下一页</a></li>
        <li class="gotopage" data-page="3"><a href="javascript:void(0);" class="page-link next">尾页</a></li>
        <li class=""><input id="goPages" placeholder="跳转页数" value=""><b class="page-link">跳转页</b></li>
    </ul>
</div>
-->
<div class='tableView'>
    <input type="hidden" id="loadUrl" value="{:U('Users/index')}">
    <input type="hidden" id="showpage" value="{$showpage}" />
    <div style="border-bottom: 1px solid #008000;border-top: 1px solid #008000;text-align: center;font-weight: bold;">
        <div style="margin: 12px auto;">
            省/市:<input type="text" name="table_search" id="searchname" value="{$searchValue}">
            <input type="button" class="bottom" value="查询">
        </div>
    </div>    
    <table class="bordered">
        <thead>
            <tr>
                <th style='width: 30px;text-align: center;'>ID</th>
                <th>用户头像</th>
                <th>用户昵称</th>
                <th>用户手机</th>
                <th>注册时间</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
        </thead>
        <?php $inum = ($showpage - 1) * 20; ?>
        <volist name="list" id="data">
            <?php $inum++; ?> 
            <tr>
                <td style='width: 30px;text-align: center;'>{$inum}</td>
                <td><img src='{$data.mlogo}' style='width: 40px;height: 40px;'></td>
                <td>{$data.nickname}</td>
                <td>{$data.mtel}</td>
                <td><span class="label label-success">{$data.mpass}</span></td>
                <td>{$data.ctime|date="y-m-d H:i:s",###}</td>
                <td></td>
            </tr>
        </volist>
    </table>
</div>
<div id="paging1" class="page light-theme simple-pagination"><ul>{$pageView}</ul></div>

<script src="__JS__/clickOpeation.js" type="text/javascript"></script>