<!--头部区域-->
<header class="layout">
    <section class="header">
        <hgroup>
            <h1>在线系统</h1>
            <!--<h2>ThinkPHP在线系统</h2>-->
        </hgroup>
        <ul class="operation">
            <!--<li><a href="#"><i class="icon icon-file-chm"></i>下载CHM版</a></li>-->
            <!--<li><a href="#"><i class="icon icon-file-pdf"></i>下载PDF版</a></li>--> 
            <li class="user">
                <a class="Is_Login" href="javascript:;">欢迎 <i>{$_SESSION["Is_Login"]} </i> <b><?php if((int)$_SESSION['purviewids'] > 0){ echo "超级管理员";}else{ echo "管理员";}  ?> </b> </a>
                <a href="{:U('Login/loginout')}">退出系统</a>
                <!-- <a href="/user/register.html">注册</a> -->                
            </li>
        </ul>
    </section>
</header>
<!--左侧导航区域-->
<aside class="layout">
    <nav data-url="/manual_3_2.html" class="thinktree thinktree-default">
        <!--<div class=""><i class="startIn"></i>EF信息管理中心</div>-->
        <ul class="thinktree-showline thinktree-root">
            <li data-id="1" data-name="preface" class="startInClass">
                <div class="div-tree-icon-switch"><a href="javascript:void(0);" onclick="window.location.reload()">管理中心</a></div>
            </li>
            <!--英孚拼拼拼-->
            <li data-id="2" data-name="Tospell" class="">
                <div class="div-tree-icon-switch"><a href="javascript:void(0);">Good 信息</a></div>
                <ul>
                    <li data-id="20" data-name="Tospell_index">
                        <div><a href="{:U('Tospell/index')}" data-href="{:U('Tospell/index')}">Good 列表</a></div>
                    </li>
                </ul>       
            </li>
            <!--退出系统-->
            <li data-id="99" data-name="get_preface" class="">
                <div><a href="{:U('Login/loginout')}">退出系统</a></div>
            </li>
        </ul>
    </nav>
</aside>
