<extend name="base:base" />
<block name="headStyle">
    <style>
        .box-footer{position: relative;}
        .box-footer>.box-tools{
            position: absolute;
            left: 20px;
            top: 10px;
        }
        .col-xs-2,.col-xs-3{height: 34px;line-height: 34px;}
        .dataTables_info{text-align: right;}
    </style>
</block>
<block name="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Dashboard
                <small>Control panel</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <!--标题-->
                        <div class="box-header"><h3 class="box-title">用户列表</h3></div>
                        <!--分页器-->
                        <div class="box-footer clearfix">
                            <div class="row">
                                <div class="col-xs-4">
                                    <div class="box-tools">
                                        <form action="{:U('Users/index')}" method="post">
                                            <div class="input-group input-group-sm" style="width: 200px;">
                                                <input type="text" name="table_search" class="form-control pull-right" placeholder="Search 用户昵称" value="{$searchValue}">
                                                <div class="input-group-btn">
                                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div class="col-xs-3"></div>
                                <div class="col-xs-2"><div class="dataTables_info" id="example2_info" role="status" aria-live="polite">共{$totals}条,每页20条</div></div>
                                <div class="col-xs-3">
                                    {$show}
                                    <ul class="pagination no-margin pull-right">
                                        <li class="paginate_button"><a href="#">上一页</a></li>
                                        <li class="paginate_button active"><a href="#">1</a></li>
                                        <li class="paginate_button"><a href="#">2</a></li>
                                        <li class="paginate_button"><a href="#">3</a></li>
                                        <li class="paginate_button"><a href="#">4</a></li>
                                        <li class="paginate_button"><a href="#">5</a></li>
                                        <li class="paginate_button"><a href="#">下一页</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body table-responsive no-padding">
                            <table class="table table-hover">
                                <tbody>
                                    <tr>
                                        <th style='width: 30px;text-align: center;'>ID</th>
                                        <th>用户头像</th>
                                        <th>用户昵称</th>
                                        <th>用户手机</th>
                                        <th>注册时间</th>
                                        <th>状态</th>
                                        <th>操作</th>
                                    </tr>
                                <volist name="list" id="data">
                                    <tr>
                                        <td style='width: 30px;text-align: center;'>{$data.uid}</td>
                                        <td><img src='{$data.mlogo}' style='width: 40px;height: 40px;'></td>
                                        <td>{$data.nickname}</td>
                                        <td>{$data.mtel}</td>
                                        <td><span class="label label-success">{$data.mpass}</span></td>
                                        <td>{$data.ctime|date="y-m-d H:i:s",###}</td>
                                        <td></td>
                                    </tr>
                                </volist>
                                </tbody>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div>
</block>