<!DOCTYPE html>
<html>
    <head>
        <title>管理系统</title>
        <link href="__CSS__/main/layout.css" rel="stylesheet" type="text/css"/>
        <link href="__CSS__/main/style.css" rel="stylesheet" type="text/css"/>
        <link href="__CSS__/table/table.css" rel="stylesheet" type="text/css"/>
        <link href="__CSS__/tkstyle/style.css" rel="stylesheet" type="text/css"/>
        <script src="__JS__/main/jquery-2.0.3.min.js" type="text/javascript"></script>
        <script src="__JS__/main/jquery.thinktree.js" type="text/javascript"></script>
        <script src="__JS__/main/jquery.thinkkeyboard.js" type="text/javascript"></script>
        <script src="__JS__/main/jquery.zclip.js" type="text/javascript"></script>
        <script src="__JS__/main/prettify.js" type="text/javascript"></script>
        <script src="__JS__/main/lang-css.js" type="text/javascript"></script>
        <script src="__JS__/main/document.js" type="text/javascript"></script>
        <script src="__JS__/main/manage.js" type="text/javascript"></script>
        <script src="__JS__/main/menuInit.js" type="text/javascript"></script>
    </head>
    <body>
        <include file="base:head_nav" />
        <!--右侧内容区域-->
        <section class="layout" >
            <article class="book" data-name="preface" data-zclip="/Public/static/zclip" data-info="/edit/info.html" data-save="/edit/save.html" data-upload="/edit/upload/book/1.html">
                <!--<header><h1 style="padding-left: 50px;">title</h1><div class="description"></div></header>-->
                <section class="content" style="width: 100%;height: auto;">
                    <!--<iframe id="loadhtmls" style="width: 100%;height: 100%;" scrolling="yes" frameborder="0" src="{:U('Index/main')}"></iframe>-->
                    {$htmls}
                </section>
                <footer></footer>
            </article>
        </section>
        <!--底部区域-->
        <footer class="layout"><p class="copyright">©2016 </p></footer>
        <!--加载层-->
        <div id="loading" style="display: none;"></div>

        <script type="text/javascript">Article.init();/* 初始文档对象 */</script>
    </body>
</html>