<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>登录</title>
        <link href="__CSS__/login/style_log.css" rel="stylesheet" type="text/css"/>
        <link href="__CSS__/login/style.css" rel="stylesheet" type="text/css"/>
        <link href="__CSS__/login/userpanel.css" rel="stylesheet" type="text/css"/>
    </head>
    <body class="login">
        <div class="login_m">
            <div class="login_logo"><img src="__PUBLIC__/static_bk/images/login/logo.png" width="196" height="46" alt=""></div>
            <div class="login_boder">
                <form action="{:U('Login/loginto')}" method="post">
                    <div class="login_padding" id="login_model">
                        <h2>用户名</h2>
                        <label>
                            <input type="text" name="username" id="username" class="txt_input txt_input2" value=""/>
                        </label>
                        <h2>密码</h2>
                        <label>
                            <input type="password" name="password" id="userpwd" class="txt_input" value=""/>
                        </label>

                        <p class="forgot"><a id="iforget" href="javascript:void(0);"></a></p>
                        <div class="rem_sub">
                            <div class="rem_sub_l" style="opacity: 0;">
                                <!--<input type="checkbox" name="checkbox" id="save_me">-->
                                <label for="checkbox">Remember me</label>
                            </div>
                            <label>
                                <input type="submit" class="sub_button" name="button" id="button" value="SIGN-IN" style="opacity: 0.7;">
                            </label>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>